# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=8.0.0-1.21.4
kambrik_version=8.0.0
percale_version=1.0.0

group=io.ejekta.bountiful
java_version=21

# Deps
mod_menu_version=13.0.4

# Common
minecraft_version=1.21.4
mod_name=Bountiful
mod_author=Ejektaflex
mod_id=bountiful
license=LGPL 3.0
credits=
description=Bountiful adds bounty boards to the world.
minecraft_version_range=[1.21.4]
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.4-20241203.153920
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.4
parchment_version=2024.12.07


# Fabric
fabric_version=0.119.4+1.21.4
fabric_loader_version=0.16.14

cloth_config_version=17.0.144

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
